name: CI setup
description: Shared setup for CI jobs

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        cache: pip
        cache-dependency-path: .cirrus_requirements.txt

    - name: Install runner packages
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends xz-utils patch curl git

    - name: Install Python dependencies
      shell: bash
      run: python -m pip install -r .cirrus_requirements.txt
