#!/bin/sh

for file in $(find chrome/app/theme -name product_logo_[0-9]*.png -a ! -name *mono*); do
     size=$(basename $file | cut -d_ -f3 | sed s/\.png//)
     dest=debian/chromium/usr/share/icons/hicolor/$size\x$size/apps
     mkdir -p $dest
     cp $file $dest/chromium.png
     echo copied: $file to $dest/chromium.png
     done
