out/Release/chromium usr/lib/chromium

out/Release/*.bin usr/lib/chromium
out/Release/*.pak usr/lib/chromium
out/Release/icudtl.dat usr/lib/chromium

out/Release/resources/en-US.pak usr/lib/chromium/locales

debian/presubj usr/share/bug/chromium

debian/master_preferences usr/share/chromium

debian/chromium.xml usr/share/gnome-control-center/default-apps

debian/chromium.desktop usr/share/applications

debian/default-flags etc/chromium.d

