out/Release/chromium usr/lib/chromium

out/Release/*.so usr/lib/chromium
out/Release/*.bin usr/lib/chromium
out/Release/*.pak usr/lib/chromium
out/Release/icudtl.dat usr/lib/chromium

out/Release/resources/*.pak usr/lib/chromium/locales

debian/presubj usr/share/bug/chromium

debian/master_preferences etc/chromium.d

debian/chromium.xml usr/share/gnome-control-center/default-apps

debian/chromium.desktop usr/share/applications
