#!/usr/bin/env python3

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / 'scripts' / 'ungoogled-chromium'))
from buildkit.config import ConfigBundle
sys.path.pop(0)

def _item_generataor(config_bundle):
    for key, value in config_bundle.gn_flags.items():
        yield '='.join((key, value.replace('"', '\\"')))

if __name__ == '__main__':
    print(' '.join(_item_generataor(ConfigBundle(sys.argv[1]))), end='')
